name: 🚀 Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Release Please
    uses: equinor/ops-actions/.github/workflows/release-please-manifest.yml@af5bad1a47ab8f8c333f8910f06c1938dd962dac # v9.43.0
    permissions:
      contents: write
      pull-requests: write
      issues: write
